
// Auto-generated by generate-portfolio-data.js

export type FieldData = {
  title: string
  description: string
  images: string[]
  thumbnail: string
}

export type SubProject = {
  title: string
  thumbnail: string
  images: string[]
  description: string[]
  fields: Record<string, FieldData>
}

export type CategoryData = {
  title: string
  thumbnail: string
  projects: Record<string, SubProject>
}

export const portfolioData: Record<string, CategoryData> = {
  "kidswear": {
    "title": "kidswear",
    "thumbnail": "\\images\\portfolio\\kidswear\\thumbnail.jpg",
    "projects": {
      "project1": {
        "title": "project1",
        "thumbnail": "\\images\\portfolio\\kidswear\\project1\\thumbnail.jpg",
        "description": [
          "Description for project1"
        ],
        "images": [],
        "fields": {}
      },
      "project2": {
        "title": "project2",
        "thumbnail": "\\images\\portfolio\\kidswear\\project2\\thumbnail.jpg",
        "description": [
          "Description for project2"
        ],
        "images": [],
        "fields": {}
      },
      "project3": {
        "title": "project3",
        "thumbnail": "\\images\\portfolio\\kidswear\\project3\\thumbnail.jpg",
        "description": [
          "Description for project3"
        ],
        "images": [],
        "fields": {}
      }
    }
  },
  "menswear": {
    "title": "menswear",
    "thumbnail": "\\images\\portfolio\\menswear\\thumbnail.jpg",
    "projects": {
      "project1": {
        "title": "project1",
        "thumbnail": "\\images\\portfolio\\menswear\\project1\\thumbnail.jpg",
        "description": [
          "Description for project1"
        ],
        "images": [],
        "fields": {}
      },
      "project2": {
        "title": "project2",
        "thumbnail": "\\images\\portfolio\\menswear\\project2\\thumbnail.jpg",
        "description": [
          "Description for project2"
        ],
        "images": [],
        "fields": {}
      },
      "project3": {
        "title": "project3",
        "thumbnail": "\\images\\portfolio\\menswear\\project3\\thumbnail.jpg",
        "description": [
          "Description for project3"
        ],
        "images": [],
        "fields": {}
      }
    }
  },
  "womenswear": {
    "title": "womenswear",
    "thumbnail": "\\images\\portfolio\\womenswear\\thumbnail.jpg",
    "projects": {
      "project1": {
        "title": "project1",
        "thumbnail": "\\images\\portfolio\\womenswear\\project1\\thumbnail.jpg",
        "description": [
          "Description for project1"
        ],
        "images": [],
        "fields": {}
      },
      "project2": {
        "title": "project2",
        "thumbnail": "\\images\\portfolio\\womenswear\\project2\\thumbnail.jpg",
        "description": [
          "Description for project2"
        ],
        "images": [],
        "fields": {}
      },
      "project3": {
        "title": "project3",
        "thumbnail": "\\images\\portfolio\\womenswear\\project3\\thumbnail.jpg",
        "description": [
          "Description for project3"
        ],
        "images": [],
        "fields": {}
      }
    }
  }
}
